###

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
Find the sum of the even-valued terms.

###

ints = [1, 2]
sum  = ints[1]

even = (i) ->
  i % 2 == 0 ? true : false

sumOfEvenFibonacciTermsUnder = (limit) ->
  while sum <= limit
    term = ints[1] + ints[0]
    ints.push(term)
    sum += term if even?(term)
    ints.shift()
  console.log sum

sumOfEvenFibonacciTermsUnder(4000000)
